//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AL.Atendimento.SobConsulta.Repositorios.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www-h.localiza.com/Empresas2/servicos/CanaisWeb.svc")]
        public string AL_Atendimento_SobConsulta_Repositorios_wsCanaisWeb_CanaisWeb {
            get {
                return ((string)(this["AL_Atendimento_SobConsulta_Repositorios_wsCanaisWeb_CanaisWeb"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://reports.localiza.com/ReportServer/ReportService.asmx")]
        public string AL_Atendimento_SobConsulta_Repositorios_wsReport_ReportingService {
            get {
                return ((string)(this["AL_Atendimento_SobConsulta_Repositorios_wsReport_ReportingService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://wshom.localiza.com/Localiza/Reserva/Reservas.asmx")]
        public string AL_Atendimento_SobConsulta_Repositorios_wsReserva_Reservas {
            get {
                return ((string)(this["AL_Atendimento_SobConsulta_Repositorios_wsReserva_Reservas"]));
            }
        }
    }
}
