//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AL.Atendimento.SobConsulta.Repositorios.NRAutorizacao {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOAutenticacaoAcessoExterno", Namespace="http://schemas.datacontract.org/2004/07/Autenticacao.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class DTOAutenticacaoAcessoExterno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AreaSolicitanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AreaUsuarioReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CulturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdSessaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenAplicacaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AreaSolicitante {
            get {
                return this.AreaSolicitanteField;
            }
            set {
                if ((this.AreaSolicitanteField.Equals(value) != true)) {
                    this.AreaSolicitanteField = value;
                    this.RaisePropertyChanged("AreaSolicitante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AreaUsuarioReserva {
            get {
                return this.AreaUsuarioReservaField;
            }
            set {
                if ((this.AreaUsuarioReservaField.Equals(value) != true)) {
                    this.AreaUsuarioReservaField = value;
                    this.RaisePropertyChanged("AreaUsuarioReserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPais {
            get {
                return this.CodigoPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPaisField, value) != true)) {
                    this.CodigoPaisField = value;
                    this.RaisePropertyChanged("CodigoPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cultura {
            get {
                return this.CulturaField;
            }
            set {
                if ((object.ReferenceEquals(this.CulturaField, value) != true)) {
                    this.CulturaField = value;
                    this.RaisePropertyChanged("Cultura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdSessao {
            get {
                return this.IdSessaoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdSessaoField, value) != true)) {
                    this.IdSessaoField = value;
                    this.RaisePropertyChanged("IdSessao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Matricula {
            get {
                return this.MatriculaField;
            }
            set {
                if ((object.ReferenceEquals(this.MatriculaField, value) != true)) {
                    this.MatriculaField = value;
                    this.RaisePropertyChanged("Matricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenAplicacao {
            get {
                return this.TokenAplicacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenAplicacaoField, value) != true)) {
                    this.TokenAplicacaoField = value;
                    this.RaisePropertyChanged("TokenAplicacao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExcecaoBase", Namespace="http://schemas.datacontract.org/2004/07/Localiza.Nucleo.Util.Excecao")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AL.Atendimento.SobConsulta.Repositorios.NRAutorizacao.ExcecaoTokenInativo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AL.Atendimento.SobConsulta.Repositorios.NRAutorizacao.ExcecaoSessaoInvalida))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AL.Atendimento.SobConsulta.Repositorios.NRAutorizacao.ExcecaoTokenInvalido))]
    public partial class ExcecaoBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExcecaoTokenInativo", Namespace="http://schemas.datacontract.org/2004/07/Autenticacao.Business.Exceptions")]
    [System.SerializableAttribute()]
    public partial class ExcecaoTokenInativo : AL.Atendimento.SobConsulta.Repositorios.NRAutorizacao.ExcecaoBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExcecaoSessaoInvalida", Namespace="http://schemas.datacontract.org/2004/07/Autenticacao.Business.Exceptions")]
    [System.SerializableAttribute()]
    public partial class ExcecaoSessaoInvalida : AL.Atendimento.SobConsulta.Repositorios.NRAutorizacao.ExcecaoBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExcecaoTokenInvalido", Namespace="http://schemas.datacontract.org/2004/07/Autenticacao.Business.Exceptions")]
    [System.SerializableAttribute()]
    public partial class ExcecaoTokenInvalido : AL.Atendimento.SobConsulta.Repositorios.NRAutorizacao.ExcecaoBase {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusSessao", Namespace="http://schemas.datacontract.org/2004/07/Autenticacao.Business.Entities.Enum")]
    public enum StatusSessao : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SessaoExpirada = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SessaoExpiraEmMenosDe1Minuto = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SessaoExpiraEmMenosDe5Minutos = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SessaoExpiraEmMenosDe10Minutos = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SessaoExpiraEmMenosDe30Minutos = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SessaoExpiraEmMenosDe1Hora = 60,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SessaoExpiraEmMaisDe1Hora = 120,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NRAutorizacao.IAutorizacao")]
    public interface IAutorizacao {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutorizacao/AutenticarAcessoExterno", ReplyAction="http://tempuri.org/IAutorizacao/AutenticarAcessoExternoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AL.Atendimento.SobConsulta.Repositorios.NRAutorizacao.ExcecaoTokenInvalido), Action="http://tempuri.org/IAutorizacao/AutenticarAcessoExternoExcecaoTokenInvalidoFault", Name="ExcecaoTokenInvalido", Namespace="http://schemas.datacontract.org/2004/07/Autenticacao.Business.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(AL.Atendimento.SobConsulta.Repositorios.NRAutorizacao.ExcecaoTokenInativo), Action="http://tempuri.org/IAutorizacao/AutenticarAcessoExternoExcecaoTokenInativoFault", Name="ExcecaoTokenInativo", Namespace="http://schemas.datacontract.org/2004/07/Autenticacao.Business.Exceptions")]
        AL.Atendimento.SobConsulta.Repositorios.NRAutorizacao.DTOAutenticacaoAcessoExterno AutenticarAcessoExterno(string tokenAplicacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutorizacao/AutenticarAcessoExterno", ReplyAction="http://tempuri.org/IAutorizacao/AutenticarAcessoExternoResponse")]
        System.Threading.Tasks.Task<AL.Atendimento.SobConsulta.Repositorios.NRAutorizacao.DTOAutenticacaoAcessoExterno> AutenticarAcessoExternoAsync(string tokenAplicacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutorizacao/VerificarStatusSessaoAcessoExterno", ReplyAction="http://tempuri.org/IAutorizacao/VerificarStatusSessaoAcessoExternoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AL.Atendimento.SobConsulta.Repositorios.NRAutorizacao.ExcecaoTokenInvalido), Action="http://tempuri.org/IAutorizacao/VerificarStatusSessaoAcessoExternoExcecaoTokenInv" +
            "alidoFault", Name="ExcecaoTokenInvalido", Namespace="http://schemas.datacontract.org/2004/07/Autenticacao.Business.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(AL.Atendimento.SobConsulta.Repositorios.NRAutorizacao.ExcecaoTokenInativo), Action="http://tempuri.org/IAutorizacao/VerificarStatusSessaoAcessoExternoExcecaoTokenIna" +
            "tivoFault", Name="ExcecaoTokenInativo", Namespace="http://schemas.datacontract.org/2004/07/Autenticacao.Business.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(AL.Atendimento.SobConsulta.Repositorios.NRAutorizacao.ExcecaoSessaoInvalida), Action="http://tempuri.org/IAutorizacao/VerificarStatusSessaoAcessoExternoExcecaoSessaoIn" +
            "validaFault", Name="ExcecaoSessaoInvalida", Namespace="http://schemas.datacontract.org/2004/07/Autenticacao.Business.Exceptions")]
        AL.Atendimento.SobConsulta.Repositorios.NRAutorizacao.StatusSessao VerificarStatusSessaoAcessoExterno(string tokenAutenticado, string idSessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutorizacao/VerificarStatusSessaoAcessoExterno", ReplyAction="http://tempuri.org/IAutorizacao/VerificarStatusSessaoAcessoExternoResponse")]
        System.Threading.Tasks.Task<AL.Atendimento.SobConsulta.Repositorios.NRAutorizacao.StatusSessao> VerificarStatusSessaoAcessoExternoAsync(string tokenAutenticado, string idSessao);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAutorizacaoChannel : AL.Atendimento.SobConsulta.Repositorios.NRAutorizacao.IAutorizacao, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutorizacaoClient : System.ServiceModel.ClientBase<AL.Atendimento.SobConsulta.Repositorios.NRAutorizacao.IAutorizacao>, AL.Atendimento.SobConsulta.Repositorios.NRAutorizacao.IAutorizacao {
        
        public AutorizacaoClient() {
        }
        
        public AutorizacaoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutorizacaoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutorizacaoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutorizacaoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AL.Atendimento.SobConsulta.Repositorios.NRAutorizacao.DTOAutenticacaoAcessoExterno AutenticarAcessoExterno(string tokenAplicacao) {
            return base.Channel.AutenticarAcessoExterno(tokenAplicacao);
        }
        
        public System.Threading.Tasks.Task<AL.Atendimento.SobConsulta.Repositorios.NRAutorizacao.DTOAutenticacaoAcessoExterno> AutenticarAcessoExternoAsync(string tokenAplicacao) {
            return base.Channel.AutenticarAcessoExternoAsync(tokenAplicacao);
        }
        
        public AL.Atendimento.SobConsulta.Repositorios.NRAutorizacao.StatusSessao VerificarStatusSessaoAcessoExterno(string tokenAutenticado, string idSessao) {
            return base.Channel.VerificarStatusSessaoAcessoExterno(tokenAutenticado, idSessao);
        }
        
        public System.Threading.Tasks.Task<AL.Atendimento.SobConsulta.Repositorios.NRAutorizacao.StatusSessao> VerificarStatusSessaoAcessoExternoAsync(string tokenAutenticado, string idSessao) {
            return base.Channel.VerificarStatusSessaoAcessoExternoAsync(tokenAutenticado, idSessao);
        }
    }
}
