//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParametroUtilizacao", Namespace="http://schemas.datacontract.org/2004/07/AcessoBB.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class ParametroUtilizacao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorField, value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidacaoEmail", Namespace="http://schemas.datacontract.org/2004/07/Email.Business.Entities")]
    public enum ValidacaoEmail : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Valido = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalido = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionBase", Namespace="http://schemas.datacontract.org/2004/07/AcessoBB.Business.Exceptions")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.EmailSemAssuntoCorpo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.EnderecoEmailInvalido))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.ParametroInvalido))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.AnexoInvalido))]
    public partial class ExceptionBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoErroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoErroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoErro {
            get {
                return this.CodigoErroField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoErroField, value) != true)) {
                    this.CodigoErroField = value;
                    this.RaisePropertyChanged("CodigoErro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoErro {
            get {
                return this.DescricaoErroField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoErroField, value) != true)) {
                    this.DescricaoErroField = value;
                    this.RaisePropertyChanged("DescricaoErro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailSemAssuntoCorpo", Namespace="http://schemas.datacontract.org/2004/07/Email.Business.Exceptions")]
    [System.SerializableAttribute()]
    public partial class EmailSemAssuntoCorpo : AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.ExceptionBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnderecoEmailInvalido", Namespace="http://schemas.datacontract.org/2004/07/Email.Business.Exceptions")]
    [System.SerializableAttribute()]
    public partial class EnderecoEmailInvalido : AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.ExceptionBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParametroInvalido", Namespace="http://schemas.datacontract.org/2004/07/Email.Business.Exceptions")]
    [System.SerializableAttribute()]
    public partial class ParametroInvalido : AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.ExceptionBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnexoInvalido", Namespace="http://schemas.datacontract.org/2004/07/Email.Business.Exceptions")]
    [System.SerializableAttribute()]
    public partial class AnexoInvalido : AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.ExceptionBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Anexo", Namespace="http://schemas.datacontract.org/2004/07/Email.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class Anexo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] conteudoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] conteudo {
            get {
                return this.conteudoField;
            }
            set {
                if ((object.ReferenceEquals(this.conteudoField, value) != true)) {
                    this.conteudoField = value;
                    this.RaisePropertyChanged("conteudo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoCorpo", Namespace="http://schemas.datacontract.org/2004/07/Email.Business.Entities")]
    public enum TipoCorpo : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Html = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlainText = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmailBuildBlock.IEmail")]
    public interface IEmail {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/ValidarEmail", ReplyAction="http://tempuri.org/IEmail/ValidarEmailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.AnexoInvalido), Action="http://tempuri.org/IEmail/ValidarEmailAnexoInvalidoFault", Name="AnexoInvalido", Namespace="http://schemas.datacontract.org/2004/07/Email.Business.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.EmailSemAssuntoCorpo), Action="http://tempuri.org/IEmail/ValidarEmailEmailSemAssuntoCorpoFault", Name="EmailSemAssuntoCorpo", Namespace="http://schemas.datacontract.org/2004/07/Email.Business.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.EnderecoEmailInvalido), Action="http://tempuri.org/IEmail/ValidarEmailEnderecoEmailInvalidoFault", Name="EnderecoEmailInvalido", Namespace="http://schemas.datacontract.org/2004/07/Email.Business.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.ParametroInvalido), Action="http://tempuri.org/IEmail/ValidarEmailParametroInvalidoFault", Name="ParametroInvalido", Namespace="http://schemas.datacontract.org/2004/07/Email.Business.Exceptions")]
        AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.ValidacaoEmail ValidarEmail(System.Guid chaveUtilizacao, string email, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.ParametroUtilizacao[] parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/ValidarEmail", ReplyAction="http://tempuri.org/IEmail/ValidarEmailResponse")]
        System.Threading.Tasks.Task<AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.ValidacaoEmail> ValidarEmailAsync(System.Guid chaveUtilizacao, string email, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.ParametroUtilizacao[] parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/EnviarEmail", ReplyAction="http://tempuri.org/IEmail/EnviarEmailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.AnexoInvalido), Action="http://tempuri.org/IEmail/EnviarEmailAnexoInvalidoFault", Name="AnexoInvalido", Namespace="http://schemas.datacontract.org/2004/07/Email.Business.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.EmailSemAssuntoCorpo), Action="http://tempuri.org/IEmail/EnviarEmailEmailSemAssuntoCorpoFault", Name="EmailSemAssuntoCorpo", Namespace="http://schemas.datacontract.org/2004/07/Email.Business.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.EnderecoEmailInvalido), Action="http://tempuri.org/IEmail/EnviarEmailEnderecoEmailInvalidoFault", Name="EnderecoEmailInvalido", Namespace="http://schemas.datacontract.org/2004/07/Email.Business.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.ParametroInvalido), Action="http://tempuri.org/IEmail/EnviarEmailParametroInvalidoFault", Name="ParametroInvalido", Namespace="http://schemas.datacontract.org/2004/07/Email.Business.Exceptions")]
        void EnviarEmail(System.Guid chaveUtilizacao, string remetente, string[] destinatarios, string[] destinatariosCC, string[] destinatariosCCO, string assunto, string corpo, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.Anexo[] anexos, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.TipoCorpo tipoCorpo, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.ParametroUtilizacao[] parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/EnviarEmail", ReplyAction="http://tempuri.org/IEmail/EnviarEmailResponse")]
        System.Threading.Tasks.Task EnviarEmailAsync(System.Guid chaveUtilizacao, string remetente, string[] destinatarios, string[] destinatariosCC, string[] destinatariosCCO, string assunto, string corpo, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.Anexo[] anexos, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.TipoCorpo tipoCorpo, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.ParametroUtilizacao[] parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/EnviarEmailComImagem", ReplyAction="http://tempuri.org/IEmail/EnviarEmailComImagemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.AnexoInvalido), Action="http://tempuri.org/IEmail/EnviarEmailComImagemAnexoInvalidoFault", Name="AnexoInvalido", Namespace="http://schemas.datacontract.org/2004/07/Email.Business.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.EmailSemAssuntoCorpo), Action="http://tempuri.org/IEmail/EnviarEmailComImagemEmailSemAssuntoCorpoFault", Name="EmailSemAssuntoCorpo", Namespace="http://schemas.datacontract.org/2004/07/Email.Business.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.EnderecoEmailInvalido), Action="http://tempuri.org/IEmail/EnviarEmailComImagemEnderecoEmailInvalidoFault", Name="EnderecoEmailInvalido", Namespace="http://schemas.datacontract.org/2004/07/Email.Business.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.ParametroInvalido), Action="http://tempuri.org/IEmail/EnviarEmailComImagemParametroInvalidoFault", Name="ParametroInvalido", Namespace="http://schemas.datacontract.org/2004/07/Email.Business.Exceptions")]
        void EnviarEmailComImagem(System.Guid chaveUtilizacao, string remetente, string[] destinatarios, string[] destinatariosCC, string[] destinatariosCCO, string assunto, string corpo, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.Anexo[] anexos, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.ParametroUtilizacao[] parametros, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.Anexo[] imagens);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/EnviarEmailComImagem", ReplyAction="http://tempuri.org/IEmail/EnviarEmailComImagemResponse")]
        System.Threading.Tasks.Task EnviarEmailComImagemAsync(System.Guid chaveUtilizacao, string remetente, string[] destinatarios, string[] destinatariosCC, string[] destinatariosCCO, string assunto, string corpo, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.Anexo[] anexos, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.ParametroUtilizacao[] parametros, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.Anexo[] imagens);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmailChannel : AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.IEmail, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmailClient : System.ServiceModel.ClientBase<AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.IEmail>, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.IEmail {
        
        public EmailClient() {
        }
        
        public EmailClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmailClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.ValidacaoEmail ValidarEmail(System.Guid chaveUtilizacao, string email, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.ParametroUtilizacao[] parametros) {
            return base.Channel.ValidarEmail(chaveUtilizacao, email, parametros);
        }
        
        public System.Threading.Tasks.Task<AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.ValidacaoEmail> ValidarEmailAsync(System.Guid chaveUtilizacao, string email, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.ParametroUtilizacao[] parametros) {
            return base.Channel.ValidarEmailAsync(chaveUtilizacao, email, parametros);
        }
        
        public void EnviarEmail(System.Guid chaveUtilizacao, string remetente, string[] destinatarios, string[] destinatariosCC, string[] destinatariosCCO, string assunto, string corpo, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.Anexo[] anexos, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.TipoCorpo tipoCorpo, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.ParametroUtilizacao[] parametros) {
            base.Channel.EnviarEmail(chaveUtilizacao, remetente, destinatarios, destinatariosCC, destinatariosCCO, assunto, corpo, anexos, tipoCorpo, parametros);
        }
        
        public System.Threading.Tasks.Task EnviarEmailAsync(System.Guid chaveUtilizacao, string remetente, string[] destinatarios, string[] destinatariosCC, string[] destinatariosCCO, string assunto, string corpo, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.Anexo[] anexos, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.TipoCorpo tipoCorpo, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.ParametroUtilizacao[] parametros) {
            return base.Channel.EnviarEmailAsync(chaveUtilizacao, remetente, destinatarios, destinatariosCC, destinatariosCCO, assunto, corpo, anexos, tipoCorpo, parametros);
        }
        
        public void EnviarEmailComImagem(System.Guid chaveUtilizacao, string remetente, string[] destinatarios, string[] destinatariosCC, string[] destinatariosCCO, string assunto, string corpo, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.Anexo[] anexos, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.ParametroUtilizacao[] parametros, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.Anexo[] imagens) {
            base.Channel.EnviarEmailComImagem(chaveUtilizacao, remetente, destinatarios, destinatariosCC, destinatariosCCO, assunto, corpo, anexos, parametros, imagens);
        }
        
        public System.Threading.Tasks.Task EnviarEmailComImagemAsync(System.Guid chaveUtilizacao, string remetente, string[] destinatarios, string[] destinatariosCC, string[] destinatariosCCO, string assunto, string corpo, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.Anexo[] anexos, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.ParametroUtilizacao[] parametros, AL.Atendimento.SobConsulta.Repositorios.EmailBuildBlock.Anexo[] imagens) {
            return base.Channel.EnviarEmailComImagemAsync(chaveUtilizacao, remetente, destinatarios, destinatariosCC, destinatariosCCO, assunto, corpo, anexos, parametros, imagens);
        }
    }
}
