INSERT INTO res_sobconsulta_motivo (cd_justificativa, desc_justificativa, dt_ultima_alteracao, cd_responsavel_alteracao) VALUES (1, 'Confirmação pelo Grupo no Cluster', getdate(), '192208')
INSERT INTO res_sobconsulta_motivo (cd_justificativa, desc_justificativa, dt_ultima_alteracao, cd_responsavel_alteracao) VALUES (2, 'Confirmação por Upgrade no Cluster', getdate(), '192208')
INSERT INTO res_sobconsulta_motivo (cd_justificativa, desc_justificativa, dt_ultima_alteracao, cd_responsavel_alteracao) VALUES (3, 'Confirmação pelo Grupo na Filial', getdate(), '192208')
INSERT INTO res_sobconsulta_motivo (cd_justificativa, desc_justificativa, dt_ultima_alteracao, cd_responsavel_alteracao) VALUES (4, 'Confirmação por Upgrade na Filial', getdate(), '192208')
INSERT INTO res_sobconsulta_motivo (cd_justificativa, desc_justificativa, dt_ultima_alteracao, cd_responsavel_alteracao) VALUES (5, 'Não Confirmação pelo Grupo na Ponta', getdate(), '192208')
INSERT INTO res_sobconsulta_motivo (cd_justificativa, desc_justificativa, dt_ultima_alteracao, cd_responsavel_alteracao) VALUES (6, 'Não Confirmação pelo Grupo de Upgrade', getdate(), '192208')
INSERT INTO res_sobconsulta_motivo (cd_justificativa, desc_justificativa, dt_ultima_alteracao, cd_responsavel_alteracao) VALUES (7, 'Aguardando Confirmação Anual', getdate(), '192208')
INSERT INTO res_sobconsulta_motivo (cd_justificativa, desc_justificativa, dt_ultima_alteracao, cd_responsavel_alteracao) VALUES (8, 'Atendida Manualmente', getdate(), '192208')
INSERT INTO res_sobconsulta_motivo (cd_justificativa, desc_justificativa, dt_ultima_alteracao, cd_responsavel_alteracao) VALUES (9, 'Grupo Inativo', getdate(), '192208')
